### ISSUE TITLE
from transformers import BertLayer

### ISSUE THREAD

**Issue by yingweima2022** [shawroad/NLP_pytorch_project#42]
您好，感谢您的工作。
我用transformers时候，发现from transformers import BertLayer
BertLayer并没有在transformers中，请问是版本问题嘛

**Comment by shawroad** [comment]
嗯嗯，是版本问题。 from transformers.models.bert import BertLayer

肖 路 Lu Xiao
微博 || 广告定向召回&机制策略 || 算法工程师
新浪口袋: 肖路（xiaolu10）
工位号: 6F-C区-9列-2
手机: 18392991940
微信: NLPer001
地址: 北京市海淀区西北旺东路10号院西区8号楼新浪总部大厦  100193

**Comment by yingweima2022** [comment]
谢谢您的回复！
from transformers.models.bert import BertLayer
我这里.models没有
![image](https://user-images.githubusercontent.com/44664739/147880913-48a7682a-1f03-4a22-9cad-31d2a944f014.png)
我的版本是2.5.0
谢谢

**Comment by shawroad** [comment]
明天帮你看一下

**Comment by yingweima2022** [comment]
非常感谢！

**Comment by yingweima2022** [comment]
我刚刚升级了transformers，解决了这个问题，谢谢！
